<a href="https://colab.research.google.com/github/ProfessorQu/Pytorch-for-Deep-Learning/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Title Here

An short introduction about PyTorch and about the chosen functions. 

- `torch.zeros`
- `torch.ones`
- `torch.complex`
- function 4
- function 5

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - `torch.zeros`

First, we will discuss the `torch.zeros` function from the PyTorch library. It is able to create a tensor of a certain size and then it will fill it with zeros.

In [ ]:
# Creating a 2 high, 5 wide tensor
torch.zeros([2, 5])

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

As you can see in the example above, the `torch.zeros` function created a 2 high, 5 wide tensor full of zeros.

In [ ]:
# Creating a 2 long, 3 high, 5 wide tensor
torch.zeros([2, 3, 5])

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

Here we created a tensor of zero. Perhaps it will be difficult to understand why this is this, so let me clarify. You can visualize this tensor as a 3D box. One side is 2 wide, the other is 3 high and the last one is 5 long. It displays this tensor like this because it will be quite difficult to visualize it once we have like 25 dimensions.

In [ ]:
# It has to be one list for it to work
torch.zeros([1.2, 2, 5])

TypeError: ignored

This example breaks because the size argument has to be an array of ints. So it can't get any other datatype like floats, strings, etc. This also means it can't contain another list or tuple. It must be one list containing only integers.

This is a useful function when you need to create a boilerplate tensor. You can instantiate the shape of your data while leaving the data empty.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 2 - `torch.arange`

This function will allow you to create a 1D tensor from a start to an end number with a certain step amount between each new number. It is uninclusive, meaning if you create an array going from 0 to 10, it won't contain 10.

This is how I would implement it.
```python
def arange(start, end, step = 1):
  # Define a "tensor"
  tensor = []

  # Start at the starting number
  num = start

  # Add elements to the list until we've reached the last element
  while num < end:
    tensor.append(num)

    # Add the step
    num += step
  
  return tensor
```



In [ ]:
# Create a 1D tensor with size 10 from 0 to 9
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Here we just create a simple 1D tensor from 0 to 9.

In [ ]:
# Create a 1D tensor with size 5 from 0 to 8 with a step of 2
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

Now here we used the step parameter, if you leave it empty it will default to 1. It will start at the start number and add the step number at each next number. If that number is smaller than the end number, it will add it to the tensor.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(0, 3, 3)

tensor([0])

Here we have a step size that is equal to the end number, so it will add 0 to the list and then the next number in line, 3, will be bigger than or equal to the end number so it'll stop adding things to the list.

It's helpful for when you need a tensor that just needs a bunch of values other than one. Or if you need to use a loop and need ascending values for it.

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 3 - `torch.complex`

This is a simple way of creating complex tensors, a complex number is basically just a list of two numbers represented as one. It has a real and an imaginary part to it. It is depicted as `real+imag*j` where j is the square root of -1, that's why they are called imaginary numbers.

In [ ]:
# Example 1 - working
real = torch.tensor([1], dtype=torch.float32)
imag = torch.tensor([2], dtype=torch.float32)
t1 = torch.complex(real, imag)

Here we create a simple complex number with a real value of 1 and an imaginary value of 2.

In [ ]:
# Example 2 - working
print(t1)
print(t1.real)
print(t1.imag)
print()
print(t1 * 1.5)
print(t1.real * 3)
print(t1.imag + 5)

tensor([1.+2.j])
tensor([1.])
tensor([2.])

tensor([1.5000+3.j])
tensor([3.])
tensor([7.])


As you can see, PyTorch supports basic arithmetic operations on both the real and imaginary parts of the tensor, and even both at the same time!

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
real = torch.tensor(7)
imag = torch.tensor(4)
torch.complex(real, imag)

RuntimeError: ignored

You have to be very explicit with the types you give the complex tensor. They have to be either a float or a double, plus you only have two parts of the tensor, the real part and the imaginary part. If you want a number to store 3 values, you'll be better off increasing the size of the tensor.

It's not something you'll have to use a lot, especially in Deep Learning, but it can be helpful for the people who need it. For example the Mandelbrot set, I couldn't find anyone who used complex tensors to draw one, but I'm certain it's possible.

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 4 - `torch.reshape`

This is a function that allows you to reshape any tensor to any size you want, within bounds.

In [ ]:
# Reshape a tensor to 6, 2
t2 = torch.rand([4, 3])
print(t2)
t2.reshape([6, 2])

tensor([[0.1715, 0.8807, 0.6282],
        [0.3179, 0.1834, 0.2466],
        [0.8092, 0.3088, 0.8913],
        [0.6430, 0.2294, 0.7268]])


tensor([[0.1715, 0.8807],
        [0.6282, 0.3179],
        [0.1834, 0.2466],
        [0.8092, 0.3088],
        [0.8913, 0.6430],
        [0.2294, 0.7268]])

First, we create a tensor with random values (to see how reshape changes the values). Then we reshape the tensor from 4, 3 to 6, 2. This works because the number of items in each tensor is the same. 4 \* 3 = 12 and 6 \* 2 = 12.

In [ ]:
# Reshape the tensor to 2, -1
t2.reshape([2, 2, -1])

tensor([[[0.1715, 0.8807, 0.6282],
         [0.3179, 0.1834, 0.2466]],

        [[0.8092, 0.3088, 0.8913],
         [0.6430, 0.2294, 0.7268]]])

We can also give one element of size a -1 to have PyTorch automatically infer that dimension. In the example I said that I will use a size of 2, 2 and that PyTorch can infer the last dimension, which is obviously 3: the total number of items is 12, so 12 / 2 / 2 = 3.

In [ ]:
# You can't reshape to an invalid shape
t2.reshape(5, -1)

RuntimeError: ignored

We can't use a size of a tensor that wouldn't contain the same amount of items as the tensor that we are reshaping. So this doesn't work because 12 isn't divisible by 5.

This is a useful function for when you have to, for example, flatten all your data to input it into a neural network. Or there are a lot more uses.

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 5 - `torch.cat`

This function is a way to "add" two tensors to eachother. It doesn't do element addition, it just adds one entire tensor to the other, or sometimes even multiple tensors.

In [ ]:
t3 = torch.rand([2, 3])
print(t3)
t4 = torch.rand([4, 3])
print(t4)

tensor([[0.0217, 0.6987, 0.0688],
        [0.1527, 0.4761, 0.4032]])
tensor([[0.5952, 0.7134, 0.7430],
        [0.6658, 0.4544, 0.8456],
        [0.9178, 0.6712, 0.4708],
        [0.6829, 0.7413, 0.1981]])


In [ ]:
# Concat the two tensors along the height
torch.cat((t3, t4))

tensor([[0.0217, 0.6987, 0.0688],
        [0.1527, 0.4761, 0.4032],
        [0.5952, 0.7134, 0.7430],
        [0.6658, 0.4544, 0.8456],
        [0.9178, 0.6712, 0.4708],
        [0.6829, 0.7413, 0.1981]])

This example is a basic way of concatting two tensors. It has one tensor of width 3, and height 2, and the other one with 3 wide and 4 high. Then it concats these tensors together to a 3 wide 6 high tensor.

In [ ]:
t5 = torch.rand([5, 3])
print(t5)
t6 = torch.rand([5, 6])
print(t6)

tensor([[0.1832, 0.3991, 0.9925],
        [0.6628, 0.4219, 0.6622],
        [0.2901, 0.1759, 0.3803],
        [0.8254, 0.1326, 0.6224],
        [0.6592, 0.6631, 0.2236]])
tensor([[0.7866, 0.6822, 0.5209, 0.0275, 0.3042, 0.5677],
        [0.9235, 0.8758, 0.6734, 0.2600, 0.7665, 0.0113],
        [0.1334, 0.9238, 0.3691, 0.5140, 0.9085, 0.1270],
        [0.1376, 0.2512, 0.8958, 0.5218, 0.5244, 0.3537],
        [0.2862, 0.9076, 0.5320, 0.6301, 0.5425, 0.4005]])


In [ ]:
# Concat the two tensors along the width
torch.cat((t5, t6), 1)

tensor([[0.1832, 0.3991, 0.9925, 0.7866, 0.6822, 0.5209, 0.0275, 0.3042, 0.5677],
        [0.6628, 0.4219, 0.6622, 0.9235, 0.8758, 0.6734, 0.2600, 0.7665, 0.0113],
        [0.2901, 0.1759, 0.3803, 0.1334, 0.9238, 0.3691, 0.5140, 0.9085, 0.1270],
        [0.8254, 0.1326, 0.6224, 0.1376, 0.2512, 0.8958, 0.5218, 0.5244, 0.3537],
        [0.6592, 0.6631, 0.2236, 0.2862, 0.9076, 0.5320, 0.6301, 0.5425, 0.4005]])

Here we concat two tensors wit ha height of 5 along the 1 dimension or the height (increasing the width).

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.cat((t5, t6))

RuntimeError: ignored

We can't concat two tensors along an axis which they do not match. So for example here they are of size 3 and 6 which do not match, so it can't concat the tensors.

This is very helpful if you have multiple tensors with important data and want to merge all those tensors together.

In [ ]:
jovian.commit(project='01-tensor-operations')

## Conclusion

We took a look at a few functions for PyTorch tensors and looked at what we can do with those functions. This was just made mostly for myself to get a basic understanding of some of the functions in the PyTorch framework.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* Complex numbers: https://pytorch.org/docs/stable/complex_numbers.html
* Mandelbrot set using PyTorch: https://medium.com/@krzysztof.pieranski/mandelbrot-set-with-pytorch-d006827fb887

In [ ]:
jovian.commit(project='01-tensor-operations')